account/urls.py
from django.urls import path
from . import views
app_name ="account"
urlpatterns=[
  path("login",views.s_login,name="login"),
  path('signin',views.s_signin,name="signin"),
  path("logout",views.s_logout,name="logout"),
  path("profile",views.s_profile,name="profile"),
  path("edit",views.edit_user,name="edit")
]

blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('details/<slug:slug>', views.blog_details.as_view(), name='dtails'),
    path('list', views.blog_list.as_view(), name='list'),
    path('category/<int:pk>', views.list_cstegory, name='list_category'),
    path('sidbar', views.sidbar, name='sidbar'),
    # path('serch', views.serch, name='serch'),
    path('contact', views.Contact.as_view(), name='contact'),
    path('like/<slug:slug>/<int:pk>', views.like, name='like')
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include("home_app.urls")),
    path("account/",include('account.urls')),
    path('blog/',include("blog.urls")),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

templates/includes/footer.html
{% load static %}
<footer class="footer-area ptb-50">
    <div class="container">
        <div class="footer-wrap">


            <p> بکند کدنویسی شده با django <i class="bx bxs-heart"></i> توسط Ramezani</p>
        </div>

        <div class="row">
            <div class="col-lg-6">
                <ul class="important-links">
                    <li>
                        <a href="about.html">
                            درباره من.
                        </a>
                    </li>
                    <li>
                        <a href="contact.html">
                               09300422245ارتباط
                        </a>
                    </li>

                </ul>
            </div>

            <div class="col-lg-6">
                <ul class="social">
                    <li>
                        <a href="#" target="_blank">
                            <i class="bx bxl-facebook"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#" target="_blank">
                            <i class="bx bxl-twitter"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#" target="_blank">
                            <i class="bx bxl-linkedin"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#" target="_blank">
                            <i class="bx bxl-youtube"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#" target="_blank">
                            <i class="bx bxl-instagram"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

templates/includes/footer_refrences.html
{% load static %}
<!-- Start Go Top Area -->
<div class="go-top">
    <i class='bx bx-chevrons-up'></i>
    <i class='bx bx-chevrons-up'></i>
</div>
<!-- End Go Top Area -->


<!-- Jquery-3.5.1.Slim.Min.JS -->
<script src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
<!-- Popper JS -->
<script src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Meanmenu JS -->
<script src="{% static 'js/jquery.meanmenu.js' %}"></script>
<!-- Wow JS -->
<script src="{% static 'js/wow.min.js' %}"></script>
<!-- Owl Carousel JS -->
<script src="{% static 'js/owl.carousel.js' %}"></script>
<!-- Owl Magnific JS -->
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<!-- Nice Select JS -->
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<!-- Form Validator JS -->
<script src="{% static 'js/form-validator.min.js' %}"></script>
<!-- Contact JS -->
<script src="{% static 'js/contact-form-script.js' %}"></script>
<!-- Ajaxchimp JS -->
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<!-- Custom JS -->
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/ajex.js' %}"></script>

templates/includes/head_refrences.html
{% load static %}


<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
<!-- Owl Theme Default CSS -->
<link rel="stylesheet" href="{% static  "css/owl.theme.default.min.css" %}">
<!-- Owl Carousel CSS -->
<link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
<!-- Owl Magnific CSS -->
<link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">
<!-- Boxicons CSS -->
<link rel="stylesheet" href="{% static "https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css" %}">
<!-- Flaticon CSS -->
<link rel="stylesheet" href="{% static "css/flaticon.css" %}">
<!-- Meanmenu CSS -->
<link rel="stylesheet" href="{% static "css/meanmenu.css" %}">
<!-- Nice Select CSS -->
<link rel="stylesheet" href="{% static "css/nice-select.css" %}">
<!-- Style CSS -->
<link rel="stylesheet" href="{% static "css/style.css" %}">
<!-- Dark mode -->
<link rel="stylesheet" href="{% static 'css/dark.css' %}">
<!-- Responsive C		<link rel="stylesheet" href="css/responsive.css">
<!-- Rtl CSS -->
<link rel="stylesheet" href="{% static "css/rtl.css" %}">
<!-- Favicon -->
<link rel="icon" type="image/png" href="{% static "img/favicon.png" %}">

<!-- Title -->
<title>
    {% block title %}
    {% endblock %}
</title>

templates/includes/header.html
{% load static %}
<header class="header-area">
    <!-- Start Navbar Area -->
    <div class="nav-area nav-area-three">
        <div class="navbar-area">
            <!-- Menu For Mobile Device -->
            <div class="mobile-nav">
                <a href="{% static "index.html" %}" class="logo">
{#                    <img src="{% static "img/logo.png" %}" alt="Logo">#}
                </a>
            </div>

            <!-- Menu For Desktop Device -->
            <div class="main-nav">
                <nav class="navbar navbar-expand-md">
                    <div class="container-fluid">
                        <div class="collapse navbar-collapse mean-menu">
                            <ul class="navbar-nav m-auto">


                                <li class="nav-item">
                                    <a href="about.html" class="nav-link">درباره من</a>
                                </li>

                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        صفحات داخلی
                                        <i class="bx bx-chevron-down"></i>
                                    </a>

                                    <ul class="dropdown-menu">
{#                                        <li class="nav-item">#}
{#                                            <a href="#" class="nav-link">#}
{#                                                نوع پست#}
{#                                                <i class="bx bx-chevron-left"></i>#}
                                            </a>

                                            <ul class="dropdown-menu">

                                            </ul>
                                        </li>

{#                                        <li class="nav-item">#}
{#                                            <a href="#" class="nav-link">#}
{#                                                فروشگاه#}
{#                                                <i class="bx bx-chevron-left"></i>#}
{#                                            </a>#}

{#                                            #}
                                        </li>

                                        <li class="nav-item">
                                            <a href="#" class="nav-link">
                                                نوع وبلاگ
                                                <i class="bx bx-chevron-left"></i>
                                            </a>

                                            <ul class="dropdown-menu">
                                                
                                                <li class="nav-item">
                                                    <a href={% url 'blog:list' %} class="nav-link"> لیست بلاگ ها  </a>
                                                </li>
                                              
                                                <li class="nav-item">
                                                    <a href="video.html" class="nav-link">ویدیو</a>
                                                </li>
                                            </ul>
                                        </li>

                                        <li class="nav-item">
                                            <a href="#" class="nav-link">
                                                کاربر
                                                <i class="bx bx-chevron-left"></i>
                                            </a>

                                            <ul class="dropdown-menu">
                                                {% if request.user.is_authenticated %}
                                                    <li class="nav-item">
                                                        <a href="{% url 'account:profile' %}" class="nav-link">پروفایل
                                                            کاربر</a>
                                                    </li>
                                                    <li class="nav-item">
                                                        <a href="{% url 'account:logout' %}" class="nav-link">خروج</a>
                                                    </li>
                                                {% else %}
                                                    <li class="nav-item">
                                                        <a href="{% url "account:login" %}" class="nav-link">ورود</a>
                                                    </li>
                                                    <li class="nav-item">
                                                        <a href="{% url 'account:signin' %}" class="nav-link">ثبت
                                                            نام </a>
                                                    </li>
                                                    <li class="nav-item">
                                                    <a href="recover-password.html" class="nav-link">فراموشی رمز
                                                        عبور</a>
                                                {% endif %}
                                                </li>

                                            </ul>
                                        </li>

                                        <li class="nav-item">
                                            <a href="review.html" class="nav-link">نظر کاربران</a>
                                        </li>

                                        <li class="nav-item">
                                            <a href="author.html" class="nav-link">صفحه نویسنده</a>
                                        </li>


                                    </ul>
                                </li>

                                <li class="nav-item logo">
                                    <a href="minimal.html" class="nav-link">
                                        <img src="{% static "img/logo.png" %}" alt="Image">
                                    </a>
                                </li>



                                <li class="nav-item">
                                    <a href="{% url 'blog:contact' %}" class="nav-link">ارتباط</a>
                                </li>
                            </ul>


                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <!-- End Navbar Area -->
</header>

templates/includes/sidebar.html
{% load static %}
<section class="blog-details-area left-sidebar ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="blog-details-right-area">
                    <div class="blog-widget search-widget">
                        <h3 class="title">جستجو</h3>
{#                        <form class="search-form" action="mm.php">#}
{#                            <input type="search" class="form-control" placeholder="قسمتی از عنوان مقاله را وارد کنید ..." name="serch" value="{% if request.GET.serch %}{{ request.GET.serch }}#}
{#                            {% endif %} ">#}
{#                            <button type="submit" >#}
{#                                <i class="bx bx-search"></i>#}
{#                            </button>#}
{#                        </form>#}
                    </div>

                    <div class="blog-widget resent-post-widget">
                        <h3 class="title">پست های اخیر</h3>
                        <ul>
                            {% for item in recent_article %}
                                <li>
                                    <a href="{% url 'blog:dtails' item.slug %}">
                                        <img src="" alt="Image">
                                        <span>{{ item.created }}</span>
                                        <h3>{{ item.title }}</h3>
                                    </a>
                                </li>
                            {% endfor %}


                        </ul>
                    </div>

{#                    <div class="blog-widget archives-widget">#}
{#                        <h3 class="title">آرشیو</h3>#}
{#                        <ul>#}
{#                            <li>#}
{#                                <a href="#">#}
{#                                    فروردین#}
{#                                    <span>1401</span>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">#}
{#                                    اردیبهشت#}
{#                                    <span>1401</span>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">#}
{#                                    خرداد#}
{#                                    <span>1401</span>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">#}
{#                                    تیر#}
{#                                    <span>1401</span>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">#}
{#                                    مرداد#}
{#                                    <span>1401</span>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">#}
{#                                    شهریور#}
{#                                    <span>1401</span>#}
{#                                </a>#}
{#                            </li>#}
{#                        </ul>#}
{#                    </div>#}

                    <div class="blog-widget categories-widget">
                        <h3 class="title">دسته بندی ها</h3>
                        <ul>
                            {% for cat in category %}
                                <li>
                                    <a href="{% url 'blog:list_category' cat.id %}">
                                        {{ cat.title }}
                                        <span>{{ cat.created.Year }}</span>
                                    </a>
                                </li>
                            {% endfor %}


                        </ul>
                    </div>
                </div>
            </div>