blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('details/<slug:slug>', views.blog_details.as_view(), name='dtails'),
    path('list', views.blog_list.as_view(), name='list'),
    path('category/<int:pk>', views.list_cstegory, name='list_category'),
    path('sidbar', views.sidbar, name='sidbar'),
    # path('serch', views.serch, name='serch'),
    path('contact', views.Contact.as_view(), name='contact'),
    path('like/<slug:slug>/<int:pk>', views.like, name='like')
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include("home_app.urls")),
    path("account/",include('account.urls')),
    path('blog/',include("blog.urls")),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

home_app/urls.py
from django.urls import path
from . import views
app_name="home_app"
urlpatterns=[
    path("",views.home,name="index"),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import format_html
from django.utils.text import slugify

class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name="عنوان")
    created = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ساخت")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها "

class Article (models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE, verbose_name="نویسنده")
    title = models.CharField(max_length=70, verbose_name="عنوان")
    category = models.ManyToManyField(Category,related_name='articles', verbose_name="دسته")
    body = models.TextField(verbose_name="متن")
    image = models.ImageField(upload_to="image/article", verbose_name="تصویر")
    created = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ساخت ")
    update = models.DateTimeField(auto_now=True, verbose_name="اخرین به روز رسانی")
    summary = models.CharField(max_length=20, verbose_name="خلاصه")
    slug = models.SlugField(null=True, unique=True)



    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        self.slug = slugify(self.title)
        if self.body :
            self.summary = self.body[20]
        super(Article,self).save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:dtails', kwargs={'slug': self.slug})



    def show_image(self):
        if self.image:
            return format_html(f'<img src="{self.image.url}" width="70px" height="60px">')

    class Meta :
        ordering = ('-created',)
        verbose_name = "مقاله"
        verbose_name_plural = "مفالات"




class Comment (models.Model) :
    article = models.ForeignKey(Article,on_delete=models.CASCADE , related_name='comment', verbose_name="مقاله")
    user = models.ForeignKey(User,on_delete=models.CASCADE , related_name='user', verbose_name="کاربر")
    text = models.TextField(verbose_name="کامنت")
    created = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ")
    parent = models.ForeignKey('self',null=True, blank=True, on_delete=models.CASCADE, related_name='reply')


    @property
    def __str__(self):
        return  self.text[:5]

    class Meta:
        verbose_name = "کامنت"
        verbose_name_plural = "کامنت ها "

class Massage(models.Model):
    name = models.CharField(max_length=50, verbose_name="نام")
    email = models.EmailField(verbose_name="ایمیل")
    phonnumber = models.IntegerField(verbose_name="شماره تلفن")
    titl = models.CharField(max_length=30, verbose_name="عنوان")
    body = models.TextField(verbose_name="متن پیام")

    def __str__(self):
        return self.titl[:5]


    class Meta :
        verbose_name = "پیام"
        verbose_name_plural = "پیام ها "


class Like(models.Model) :
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="like", verbose_name="کاربر")
    article = models.ForeignKey(Article,on_delete=models.CASCADE, related_name="like", verbose_name="مقاله")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}--{self.article.title}"

    class Meta:
        verbose_name = "لایک"
        verbose_name_plural = "لایک ها"

blog/forms.py
from django import forms
from  . import models


class MassageForm(forms.ModelForm):
    class Meta:
        model = models.Massage
        fields = '__all__'
        widgets = {
            "name": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'نام'
            }),
            "email": forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'ایمیل'
            }),
            "phonnumber": forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'شماره تلفن'
            }),
            "titl": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'موضوع'
            }),
            "body": forms.Textarea(attrs={
                'placeholder': 'متن'
            })

        }

blog/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Article, Category, Comment, Like
from django.core.paginator import Paginator
from  .forms import MassageForm
from django.views.generic import ListView, DetailView , FormView
from .models import Massage
from .mixins import LoginRequestMixin
# def b_details (request,slug) :
#     article = get_object_or_404(Article, slug=slug)
#     if request.method == 'POST':
#         text = request.POST.get('text_body')
#         parent_id = request.POST.get('parent')
#         Comment.objects.create(text=text,user=request.user,article=article,parent_id=parent_id)
#     return render(request, 'blog/article_detail.html', {'article': article})
# def list_blog (request) :
#     article = Article.objects.all()
#     page_number = request.GET.get('page')
#     paginator = Paginator(article, 1)
#     object_list = paginator.get_page(page_number)
#     return render(request, 'blog/article_list.html', {'article': object_list })

def list_cstegory(request,pk) :
    category = get_object_or_404(Category, id=pk)
    article = category.articles.all()
    return render(request, "blog/category_article_list.html", {'article':article})

def sidbar (request):
    return render(request, "includes/sidebar.html", {})


# def serch(request):   سرچ تابع
#     s = request.GET.get('serch')
#     result = Article.objects.filter(title__icontains=s)
#     page_number = request.GET.get('page')
#     paginator = Paginator(result, 1)
#     object_list = paginator.get_page(page_number)
#     return  render(request, 'blog/article_list.html', {'article': object_list})

# def contact (request):
#
#
#     if request.method == 'POST':
#         form = MassageForm(data=request.POST)
#         if form.is_valid():
#             text = form.cleaned_data['text']
#             print(text)
#     else:
#         form = MassageForm()
#
#     return render(request,'blog/contact.html',{'form':form})


class blog_list (LoginRequestMixin, ListView):
  model = Article
  paginate_by = 1



class blog_details (DetailView):
    model = Article
    context_object_name = "article"
    def post_redirect_url(self):
        text = self.request.POST.get('text_body')
        parent_id = self.request.POST.get('parent')
        Comment.objects.create(text=text,user=self.request.user,article=self.request,parent_id=parent_id)
    def get_context_data(self, **kwargs):
        if self.request.user.is_authenticated:
            context = super().get_context_data(**kwargs)

            if self.request.user.like.filter(article__slug=self.object.slug , user__id=self.request.user.id).exists():
                context['liked'] = True
            else:
                context ['iked'] = False
            return context


class Contact (FormView):
    template_name = 'blog/contact.html'
    form_class = MassageForm
    success_url = "/"
    def form_valid(self, form):
        form_data = form.cleaned_data
        Massage.objects.create(**form_data)
        return super().form_valid(form)


def like(request, slug , pk):
    if request.user.is_authenticated:
        try:
            like = Like.objects.get(article__slug=slug , user__id=request.user.id)
            like.delete()
            return JsonResponse({'response':'onliked'})
        except:
            Like.objects.create(article_id=pk, user_id=request.user.id)
            return JsonResponse({'response': 'liked'})

blog/templates/blog/article_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% load render_partial %}
    <!-- Sidebar Modal Area -->
    <div class="sidebar-modal">
        <div class="sidebar-modal-inner">
            <div class="sidebar-about-area">
                <div class="title">
                    <h2>درباره ما</h2>
                    <p>ما معتقدیم تعامل با برند در ارتباطات کلیدی است. نوآوری های واقعی و تجربه مثبت مشتری قلب ارتباط
                        موفق
                        است. بدون محصولات و خدمات تقلبی مشتری پادشاه است، زندگی و نیازهای آنها الهام بخش است.</p>
                </div>
            </div>

            <div class="sidebar-instagram-feed">
                <h2>وبلاگ</h2>

                <ul>
                    <li>
                        <a href="blog-details.html">
                            <img src="{% static 'img/travel-page-img/sidebar-img/1.jpg' %}" alt="image">
                        </a>
                    </li>
                    <li>
                        <a href="blog-details.html">
                            <img src="{% static 'img/travel-page-img/sidebar-img/2.jpg' %}" alt="image">
                        </a>
                    </li>
                    <li>
                        <a href="blog-details.html">
                            <img src="{% static 'img/travel-page-img/sidebar-img/3.jpg' %}" alt="image">
                        </a>
                    </li>
                    <li>
                        <a href="blog-details.html">
                            <img src="{% static 'img/travel-page-img/sidebar-img/4.jpg' %}" alt="image">
                        </a>
                    </li>
                    <li>
                        <a href="blog-details.html">
                            <img src="{% static 'img/travel-page-img/sidebar-img/5.jpg' %}" alt="image">
                        </a>
                    </li>
                    <li>
                        <a href="blog-details.html">
                            <img src="{% static 'img/travel-page-img/sidebar-img/6.jpg' %}" alt="image">
                        </a>
                    </li>
                    <li>
                        <a href="blog-details.html">
                            <img src="{% static 'img/travel-page-img/sidebar-img/7.jpg' %}" alt="image">
                        </a>
                    </li>
                    <li>
                        <a href="blog-details.html">
                            <img src="{% static 'img/travel-page-img/sidebar-img/8.jpg' %}" alt="image">
                        </a>
                    </li>
                </ul>
            </div>

            <div class="sidebar-contact-area">
                <div class="contact-info">
                    <div class="contact-info-content">
                        <h2>
                            <a href="tel:+61-821-456">+61-821-456</a>
                            <span>OR</span>
                            <a href="mailto:hello@trice.com">hello@osta.com</a>
                        </h2>

                        <ul class="social">
                            <li>
                                <a href="#" target="_blank">
                                    <i class="bx bxl-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" target="_blank">
                                    <i class="bx bxl-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" target="_blank">
                                    <i class="bx bxl-linkedin"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" target="_blank">
                                    <i class="bx bxl-youtube"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" target="_blank">
                                    <i class="bx bxl-instagram"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <span class="close-btn sidebar-modal-close-btn">
					<i class="bx bx-x"></i>
				</span>
        </div>
    </div>
    <!-- End Sidebar Modal Area -->

    <!-- Start Page Title Area -->
    <div class="page-title-area bg-3">
        <div class="container">
            <div class="page-title-content">
                <h2>لیست مقالات</h2>
                <ul>
                    <li>
                        <a href="{% url "home_app:index" %}">
                            خانه
                        </a>
                    </li>

                    <li class="active">لیست مقالات</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- End Page Title Area -->
    {% render_partial 'blog:sidbar' %}

    <div class="col-lg-8">
        <div class="row">

            {% for article in object_list %}


                <div class="col-lg-6 col-md-6">
                    <div class="single-featured">
                        <a href="{% url 'blog:dtails' article.slug %}">
                            <img src="{{ article.image.url }}" alt="Image">
                        </a>

                        <div class="featured-content">
                            <ul class="date">
                                <li>
                                    {{ article.created }}
                                </li>
                                <li>
                                    {{ article.category.all.first }}
                                </li>
                            </ul>

                            <a href="{% url 'blog:dtails' article.slug %}">
                                <h3>{{ article.title }}</h3>
                            </a>
                            <p>{{ article.summary }}</p>

                            <a href="{% url 'blog:dtails' article.slug %}" class="read-more">
                                ادامه مطلب
                            </a>
                        </div>
                    </div>
                </div>

            {% endfor %}


            <div class="col-lg-12 col-md-12">
                {% if page_obj.has_other_pages %}
                    <div class="pagination-area text-center">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.serch %}&serch={{ request.GET.serch }}
                            {% endif %} " class="prev page-numbers">قبلی</a>
                        {% endif %}
                        {% for item in page_obj.paginator.page_range %}
                            {% if page_obj.number == item %}
                                <span class="page-numbers current" aria-current="page">{{ item }}</span>
                            {% else %}
                                <a href="?page={{ item }}{% if request.GET.serch %}&serch={{ request.GET.serch }}
                            {% endif %}" class="page-numbers">{{ item }}</a>
                            {% endif %}

                        {% endfor %}

                        {% if page_obj.has_next %}
                            <a href="?page={{page_obj.next_page_number}}{% if request.GET.serch %}&serch={{ request.GET.serch }}
                            {% endif %}" class="next page-numbers">بعدی</a>
                        {% endif %}

                    </div>
                {% endif %}


            </div>
        </div>
    </div>
    </div>
    </div>
    </section>



{% endblock %}

blog/templates/blog/category_article_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% load render_partial %}
    <!-- Sidebar Modal Area -->
    <div class="sidebar-modal">
        <div class="sidebar-modal-inner">
            <div class="sidebar-about-area">
                <div class="title">
                    <h2>درباره ما</h2>
                    <p>ما معتقدیم تعامل با برند در ارتباطات کلیدی است. نوآوری های واقعی و تجربه مثبت مشتری قلب ارتباط
                        موفق
                        است. بدون محصولات و خدمات تقلبی مشتری پادشاه است، زندگی و نیازهای آنها الهام بخش است.</p>
                </div>
            </div>

            <div class="sidebar-instagram-feed">
                <h2>وبلاگ</h2>

                <ul>
                    <li>
                        <a href="blog-details.html">
                            <img src="{% static 'img/travel-page-img/sidebar-img/1.jpg' %}" alt="image">
                        </a>
                    </li>
                    <li>
                        <a href="blog-details.html">
                            <img src="{% static 'img/travel-page-img/sidebar-img/2.jpg' %}" alt="image">
                        </a>
                    </li>
                    <li>
                        <a href="blog-details.html">
                            <img src="{% static 'img/travel-page-img/sidebar-img/3.jpg' %}" alt="image">
                        </a>
                    </li>
                    <li>
                        <a href="blog-details.html">
                            <img src="{% static 'img/travel-page-img/sidebar-img/4.jpg' %}" alt="image">
                        </a>
                    </li>
                    <li>
                        <a href="blog-details.html">
                            <img src="{% static 'img/travel-page-img/sidebar-img/5.jpg' %}" alt="image">
                        </a>
                    </li>
                    <li>
                        <a href="blog-details.html">
                            <img src="{% static 'img/travel-page-img/sidebar-img/6.jpg' %}" alt="image">
                        </a>
                    </li>
                    <li>
                        <a href="blog-details.html">
                            <img src="{% static 'img/travel-page-img/sidebar-img/7.jpg' %}" alt="image">
                        </a>
                    </li>
                    <li>
                        <a href="blog-details.html">
                            <img src="{% static 'img/travel-page-img/sidebar-img/8.jpg' %}" alt="image">
                        </a>
                    </li>
                </ul>
            </div>

            <div class="sidebar-contact-area">
                <div class="contact-info">
                    <div class="contact-info-content">
                        <h2>
                            <a href="tel:+61-821-456">+61-821-456</a>
                            <span>OR</span>
                            <a href="mailto:hello@trice.com">hello@osta.com</a>
                        </h2>

                        <ul class="social">
                            <li>
                                <a href="#" target="_blank">
                                    <i class="bx bxl-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" target="_blank">
                                    <i class="bx bxl-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" target="_blank">
                                    <i class="bx bxl-linkedin"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" target="_blank">
                                    <i class="bx bxl-youtube"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" target="_blank">
                                    <i class="bx bxl-instagram"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <span class="close-btn sidebar-modal-close-btn">
					<i class="bx bx-x"></i>
				</span>
        </div>
    </div>
    <!-- End Sidebar Modal Area -->

    <!-- Start Page Title Area -->
    <div class="page-title-area bg-3">
        <div class="container">
            <div class="page-title-content">
                <h2>لیست مقالات</h2>
                <ul>
                    <li>
                        <a href="{% url "home_app:index" %}">
                            خانه
                        </a>
                    </li>

                    <li class="active">لیست مقالات</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- End Page Title Area -->
    {% render_partial 'blog:sidbar' %}

    <div class="col-lg-8">
        <div class="row">

            {% for article in article %}


                <div class="col-lg-6 col-md-6">
                    <div class="single-featured">
                        <a href="{% url 'blog:dtails' article.slug %}">
                            <img src="{{ article.image.url }}" alt="Image">
                        </a>

                        <div class="featured-content">
                            <ul class="date">
                                <li>
                                    {{ article.created }}
                                </li>
                                <li>
                                    {{ article.category.all.first }}
                                </li>
                            </ul>

                            <a href="{% url 'blog:dtails' article.slug %}">
                                <h3>{{ article.title }}</h3>
                            </a>
                            <p>{{ article.summary }}</p>

                            <a href="{% url 'blog:dtails' article.slug %}" class="read-more">
                                ادامه مطلب
                            </a>
                        </div>
                    </div>
                </div>

            {% endfor %}


            <div class="col-lg-12 col-md-12">
                {% if page_obj.has_other_pages %}
                    <div class="pagination-area text-center">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.serch %}&serch={{ request.GET.serch }}
                            {% endif %} " class="prev page-numbers">قبلی</a>
                        {% endif %}
                        {% for item in page_obj.paginator.page_range %}
                            {% if page_obj.number == item %}
                                <span class="page-numbers current" aria-current="page">{{ item }}</span>
                            {% else %}
                                <a href="?page={{ item }}{% if request.GET.serch %}&serch={{ request.GET.serch }}
                            {% endif %}" class="page-numbers">{{ item }}</a>
                            {% endif %}

                        {% endfor %}

                        {% if page_obj.has_next %}
                            <a href="?page={{page_obj.next_page_number}}{% if request.GET.serch %}&serch={{ request.GET.serch }}
                            {% endif %}" class="next page-numbers">بعدی</a>
                        {% endif %}

                    </div>
                {% endif %}


            </div>
        </div>
    </div>
    </div>
    </div>
    </section>



{% endblock %}